Attribute VB_Name = "Global_Variables"
Public HRS As ADODB.Connection
Public SMS As ADODB.Connection
Public RS As ADODB.Recordset
Public UserID As String
Public PW As String
Public Division_Code, Division_Name As String
Public IDRS As ADODB.Recordset
Public Com_Code As String
Public DupRS As ADODB.Recordset
Public GRDRS As ADODB.Recordset
Public UPRS As ADODB.Recordset
Public R, C As Integer
Public V_Category As String
Public V_Cat_ID As Integer
Public V_Brand_Name As String
Public V_Model_ID As Integer
Public V_Model As String
Public Ins_Company As String
Public Ins_Company_ID As Integer
Public Distance As Long
Public Rate As Double
Public Loc_City_ID As Integer
Public Tmp As Long
Public R_Method_ID As Integer
Public Module_ID As Integer
Public Sub_Module_ID As Integer
Public Report_Path As String
Public SMS_Message As String
Public RightsMode As Integer
Public Reason_ID As Integer
Public DSN_SETTINGS As String
Public U_Com_Code As String
Public U_D_Code As Long
Public Balance_Budget As Double
Public con_ADMS As ADODB.Connection                     'ADMS Server Linked with ProMIS-SX Server due to Windows standard Edition
Public ProMIS_DSN As String
Public Province_ID As Integer
Public Medi_U_Name As String
